/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controlador.PedidoDao;
import controlador.ProdutoDao;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.ItensPedido;
import modelo.Pedido;
import modelo.Produto;

/**
 *
 * @author gabrielfiaux
 */
public class TelaRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form TelaRestaurante
     */
    public TelaRestaurante() {
        initComponents();
        atualizaTabelaProdutos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        pCabecalho = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        lblPrincipal = new javax.swing.JLabel();
        pRodaPe = new javax.swing.JPanel();
        lblTerminal = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JTabbedPane();
        pMesas = new javax.swing.JPanel();
        pMesa4 = new javax.swing.JPanel();
        lblMesa4 = new javax.swing.JLabel();
        lblValorT4 = new javax.swing.JLabel();
        lblItensP4 = new javax.swing.JLabel();
        pMesa3 = new javax.swing.JPanel();
        lblMesa3 = new javax.swing.JLabel();
        lblValorT3 = new javax.swing.JLabel();
        lblItensP3 = new javax.swing.JLabel();
        pMesa2 = new javax.swing.JPanel();
        lblMesa2 = new javax.swing.JLabel();
        lblValorT2 = new javax.swing.JLabel();
        lblItensP2 = new javax.swing.JLabel();
        pMesa1 = new javax.swing.JPanel();
        lblMesa1 = new javax.swing.JLabel();
        lblValorT1 = new javax.swing.JLabel();
        lblItensP1 = new javax.swing.JLabel();
        pMesa6 = new javax.swing.JPanel();
        lblMesa6 = new javax.swing.JLabel();
        lblValorT6 = new javax.swing.JLabel();
        lblItensP6 = new javax.swing.JLabel();
        pMesa5 = new javax.swing.JPanel();
        lblMesa5 = new javax.swing.JLabel();
        lblValorT5 = new javax.swing.JLabel();
        lblItensP5 = new javax.swing.JLabel();
        pPedidosMesa = new javax.swing.JPanel();
        lblPedidosMesa = new javax.swing.JLabel();
        spPedidosMesa = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        tfValorT = new javax.swing.JTextField();
        lblValorT = new javax.swing.JLabel();
        lblAdicionar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblRemover = new javax.swing.JLabel();
        pNovoPedido = new javax.swing.JPanel();
        lblMesa = new javax.swing.JLabel();
        cbMesa = new javax.swing.JComboBox<>();
        lblQuantidade = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JTextField();
        lblProdutos = new javax.swing.JLabel();
        spProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        lblIconAddRem = new javax.swing.JLabel();
        lblItensP = new javax.swing.JLabel();
        spItensP = new javax.swing.JScrollPane();
        tblItensP = new javax.swing.JTable();
        btnSalvarPedido = new javax.swing.JButton();
        lblValorTNovoP = new javax.swing.JLabel();
        tfValorTNovoP = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pPrincipal.setBackground(new java.awt.Color(102, 102, 102));

        pCabecalho.setBackground(new java.awt.Color(255, 255, 102));

        btnSair.setText("Exit");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/restaurante.png"))); // NOI18N

        lblPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblPrincipal.setText("Dogão do Gab");

        javax.swing.GroupLayout pCabecalhoLayout = new javax.swing.GroupLayout(pCabecalho);
        pCabecalho.setLayout(pCabecalhoLayout);
        pCabecalhoLayout.setHorizontalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pCabecalhoLayout.setVerticalGroup(
            pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCabecalhoLayout.createSequentialGroup()
                .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(lblIcon)))
                    .addGroup(pCabecalhoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPrincipal)))
                .addGap(462, 462, 462))
        );

        pRodaPe.setBackground(new java.awt.Color(204, 204, 204));

        lblTerminal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerminal.setText("Terminal:");

        lblIP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIP.setText("192.168.56.1");

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHora.setText("19:00:00");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("terça-feira 25/02/2025");

        javax.swing.GroupLayout pRodaPeLayout = new javax.swing.GroupLayout(pRodaPe);
        pRodaPe.setLayout(pRodaPeLayout);
        pRodaPeLayout.setHorizontalGroup(
            pRodaPeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRodaPeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTerminal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblData)
                .addGap(84, 84, 84)
                .addComponent(lblHora)
                .addContainerGap())
        );
        pRodaPeLayout.setVerticalGroup(
            pRodaPeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRodaPeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pRodaPeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTerminal)
                    .addComponent(lblIP)
                    .addComponent(lblHora)
                    .addComponent(lblData))
                .addContainerGap())
        );

        tabbedPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        pMesa4.setBackground(new java.awt.Color(153, 255, 153));
        pMesa4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pMesa4.setPreferredSize(new java.awt.Dimension(200, 110));

        lblMesa4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMesa4.setText("MESA 4");

        lblValorT4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorT4.setText("R$ 0,00");

        lblItensP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedido.png"))); // NOI18N

        javax.swing.GroupLayout pMesa4Layout = new javax.swing.GroupLayout(pMesa4);
        pMesa4.setLayout(pMesa4Layout);
        pMesa4Layout.setHorizontalGroup(
            pMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesa4Layout.createSequentialGroup()
                        .addComponent(lblMesa4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMesa4Layout.createSequentialGroup()
                        .addComponent(lblItensP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(lblValorT4)))
                .addContainerGap())
        );
        pMesa4Layout.setVerticalGroup(
            pMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMesa4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItensP4)
                    .addComponent(lblValorT4))
                .addContainerGap())
        );

        pMesa3.setBackground(new java.awt.Color(153, 255, 153));
        pMesa3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMesa3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMesa3.setText("MESA 3");

        lblValorT3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorT3.setText("R$ 0,00");

        lblItensP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedido.png"))); // NOI18N

        javax.swing.GroupLayout pMesa3Layout = new javax.swing.GroupLayout(pMesa3);
        pMesa3.setLayout(pMesa3Layout);
        pMesa3Layout.setHorizontalGroup(
            pMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesa3Layout.createSequentialGroup()
                        .addComponent(lblMesa3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMesa3Layout.createSequentialGroup()
                        .addComponent(lblItensP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValorT3)))
                .addContainerGap())
        );
        pMesa3Layout.setVerticalGroup(
            pMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMesa3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItensP3)
                    .addComponent(lblValorT3))
                .addContainerGap())
        );

        pMesa2.setBackground(new java.awt.Color(153, 255, 153));
        pMesa2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pMesa2.setPreferredSize(new java.awt.Dimension(200, 110));

        lblMesa2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMesa2.setText("MESA 2");

        lblValorT2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorT2.setText("R$ 0,00");

        lblItensP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedido.png"))); // NOI18N

        javax.swing.GroupLayout pMesa2Layout = new javax.swing.GroupLayout(pMesa2);
        pMesa2.setLayout(pMesa2Layout);
        pMesa2Layout.setHorizontalGroup(
            pMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesa2Layout.createSequentialGroup()
                        .addComponent(lblMesa2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMesa2Layout.createSequentialGroup()
                        .addComponent(lblItensP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(lblValorT2)))
                .addContainerGap())
        );
        pMesa2Layout.setVerticalGroup(
            pMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMesa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItensP2)
                    .addComponent(lblValorT2))
                .addContainerGap())
        );

        pMesa1.setBackground(new java.awt.Color(255, 153, 153));
        pMesa1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMesa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMesa1.setText("MESA 1");

        lblValorT1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorT1.setText("R$ 150,00");

        lblItensP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedido.png"))); // NOI18N

        javax.swing.GroupLayout pMesa1Layout = new javax.swing.GroupLayout(pMesa1);
        pMesa1.setLayout(pMesa1Layout);
        pMesa1Layout.setHorizontalGroup(
            pMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesa1Layout.createSequentialGroup()
                        .addComponent(lblMesa1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMesa1Layout.createSequentialGroup()
                        .addComponent(lblItensP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(lblValorT1)))
                .addContainerGap())
        );
        pMesa1Layout.setVerticalGroup(
            pMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMesa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItensP1)
                    .addComponent(lblValorT1))
                .addContainerGap())
        );

        pMesa6.setBackground(new java.awt.Color(255, 153, 153));
        pMesa6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pMesa6.setPreferredSize(new java.awt.Dimension(200, 110));

        lblMesa6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMesa6.setText("MESA 6");

        lblValorT6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorT6.setText("R$ 150,00");

        lblItensP6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedido.png"))); // NOI18N

        javax.swing.GroupLayout pMesa6Layout = new javax.swing.GroupLayout(pMesa6);
        pMesa6.setLayout(pMesa6Layout);
        pMesa6Layout.setHorizontalGroup(
            pMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesa6Layout.createSequentialGroup()
                        .addComponent(lblMesa6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMesa6Layout.createSequentialGroup()
                        .addComponent(lblItensP6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(lblValorT6)))
                .addContainerGap())
        );
        pMesa6Layout.setVerticalGroup(
            pMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMesa6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItensP6)
                    .addComponent(lblValorT6))
                .addContainerGap())
        );

        pMesa5.setBackground(new java.awt.Color(153, 255, 153));
        pMesa5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMesa5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMesa5.setText("MESA 5");

        lblValorT5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorT5.setText("R$ 0,00");

        lblItensP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedido.png"))); // NOI18N

        javax.swing.GroupLayout pMesa5Layout = new javax.swing.GroupLayout(pMesa5);
        pMesa5.setLayout(pMesa5Layout);
        pMesa5Layout.setHorizontalGroup(
            pMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesa5Layout.createSequentialGroup()
                        .addComponent(lblMesa5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pMesa5Layout.createSequentialGroup()
                        .addComponent(lblItensP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValorT5)))
                .addContainerGap())
        );
        pMesa5Layout.setVerticalGroup(
            pMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesa5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMesa5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblItensP5)
                    .addComponent(lblValorT5))
                .addContainerGap())
        );

        pPedidosMesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPedidosMesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPedidosMesa.setText("Pedido da Mesa");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitario", "Total"
            }
        ));
        spPedidosMesa.setViewportView(tblPedidos);

        tfValorT.setEditable(false);
        tfValorT.setText("0,00");

        lblValorT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorT.setText("Valor Total");

        lblAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N

        lblRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N

        javax.swing.GroupLayout pPedidosMesaLayout = new javax.swing.GroupLayout(pPedidosMesa);
        pPedidosMesa.setLayout(pPedidosMesaLayout);
        pPedidosMesaLayout.setHorizontalGroup(
            pPedidosMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPedidosMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPedidosMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spPedidosMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pPedidosMesaLayout.createSequentialGroup()
                        .addComponent(lblPedidosMesa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPedidosMesaLayout.createSequentialGroup()
                        .addComponent(lblAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(lblValorT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfValorT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pPedidosMesaLayout.setVerticalGroup(
            pPedidosMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPedidosMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedidosMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPedidosMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPedidosMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfValorT)
                    .addComponent(lblValorT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout pMesasLayout = new javax.swing.GroupLayout(pMesas);
        pMesas.setLayout(pMesasLayout);
        pMesasLayout.setHorizontalGroup(
            pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pMesa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMesa5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPedidosMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pMesasLayout.setVerticalGroup(
            pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pPedidosMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pMesasLayout.createSequentialGroup()
                        .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pMesa2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pMesa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pMesa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabbedPanel.addTab("Mesas", pMesas);

        lblMesa.setText("Mesa");

        cbMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        lblQuantidade.setText("Quantidade");

        tfQuantidade.setText("1");
        tfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeActionPerformed(evt);
            }
        });

        lblProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProdutos.setText("Produtos");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "UN", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        spProdutos.setViewportView(tblProdutos);
        if (tblProdutos.getColumnModel().getColumnCount() > 0) {
            tblProdutos.getColumnModel().getColumn(0).setResizable(false);
        }

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        lblIconAddRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ciclo.png"))); // NOI18N

        lblItensP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItensP.setText("Itens do Pedido");

        tblItensP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Valor UN", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spItensP.setViewportView(tblItensP);
        if (tblItensP.getColumnModel().getColumnCount() > 0) {
            tblItensP.getColumnModel().getColumn(0).setResizable(false);
        }

        btnSalvarPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnSalvarPedido.setText("Salvar Pedido");
        btnSalvarPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPedidoActionPerformed(evt);
            }
        });

        lblValorTNovoP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorTNovoP.setText("Valor Total");

        tfValorTNovoP.setEditable(false);
        tfValorTNovoP.setText("0.00");

        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNovoPedidoLayout = new javax.swing.GroupLayout(pNovoPedido);
        pNovoPedido.setLayout(pNovoPedidoLayout);
        pNovoPedidoLayout.setHorizontalGroup(
            pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNovoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNovoPedidoLayout.createSequentialGroup()
                        .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMesa)
                            .addComponent(lblQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfQuantidade)))
                    .addComponent(lblProdutos)
                    .addGroup(pNovoPedidoLayout.createSequentialGroup()
                        .addComponent(spProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pNovoPedidoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblIconAddRem))
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNovoPedidoLayout.createSequentialGroup()
                        .addComponent(btnSalvarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblValorTNovoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorTNovoP, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addComponent(spItensP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pNovoPedidoLayout.createSequentialGroup()
                        .addComponent(lblItensP)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pNovoPedidoLayout.setVerticalGroup(
            pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNovoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesa)
                    .addComponent(lblItensP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pNovoPedidoLayout.createSequentialGroup()
                        .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantidade)
                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pNovoPedidoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIconAddRem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(btnLimpar)
                                .addGap(10, 10, 10))))
                    .addComponent(spItensP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNovoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalvarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorTNovoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfValorTNovoP))
                .addContainerGap())
        );

        tabbedPanel.addTab("Novo Pedido", pNovoPedido);

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pRodaPe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel)
                .addContainerGap())
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addComponent(pCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pRodaPe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        int linhaSelecionada = tblProdutos.getSelectedRow();
        if (linhaSelecionada != -1) {
            int id = Integer.parseInt(tblProdutos.getModel().getValueAt(linhaSelecionada, 0).toString());
            String nomeProduto = tblProdutos.getModel().getValueAt(linhaSelecionada, 1).toString();
            double valorUn = Double.parseDouble(tblProdutos.getModel().getValueAt(linhaSelecionada, 3).toString());
            int quantidade = Integer.parseInt(tfQuantidade.getText());
            double valorTotal = quantidade * valorUn;

            DefaultTableModel modelo = (DefaultTableModel) tblItensP.getModel();
            String[] linhadaTabela = {
                String.valueOf(id),
                nomeProduto,
                String.valueOf(quantidade),
                String.valueOf(valorUn),
                String.valueOf(valorTotal)
            };
            modelo.addRow(linhadaTabela);

            atualizaValorTotal(valorTotal);
        } else {
            JOptionPane.showMessageDialog(null, "Necessário selecionar um produto.");
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int linhaSelecionada = tblItensP.getSelectedRow();
        if (linhaSelecionada != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tblItensP.getModel();

            double valor = Double.parseDouble(tblItensP.getModel().getValueAt(linhaSelecionada, 4).toString());
            double valorTotal = valor * -1;
            atualizaValorTotal(valorTotal);
            modelo.removeRow(linhaSelecionada);
        } else {
            JOptionPane.showMessageDialog(null, "Necessário selecionar um registro.");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnSalvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPedidoActionPerformed
        Pedido p = new Pedido();
        p.setMesa(Integer.parseInt(cbMesa.getSelectedItem().toString()));
        p.setStatus(1); //Aberta

        TableModel tabela = tblItensP.getModel();
        for (int linha = 0; linha < tabela.getRowCount(); linha++) {
            Integer id = Integer.parseInt(tabela.getValueAt(linha, 0).toString());
            Integer quantidade = Integer.parseInt(tabela.getValueAt(linha, 2).toString());
            Double valor = Double.parseDouble(tabela.getValueAt(linha, 3).toString().replaceAll(",", "."));

            Produto produto = new Produto();
            produto.setId(id);

            ItensPedido ip = new ItensPedido();
            ip.setProduto(produto);
            ip.setQuantidade(quantidade);
            ip.setValor(valor);

            p.addItemPedido(ip);
        }

        PedidoDao dao = new PedidoDao();
        try {
            dao.inserir(p);
            limparTabelaItensPedido();
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_btnSalvarPedidoActionPerformed

    private void limparTabelaItensPedido() {
        ((DefaultTableModel) tblItensP.getModel()).setRowCount(0);
        tfValorTNovoP.setText("0.00");
    }

    private void tfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Obtém a JTable dentro do JScrollPane
        JTable tabela = (JTable) spItensP.getViewport().getView();

        // Verifica se a tabela não é nula
        if (tabela != null) {
            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.setRowCount(0); // Remove todas as linhas
        }


    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRestaurante().setVisible(true);
            }
        });
    }

    private void atualizaTabelaProdutos() {
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        modelo.setNumRows(0); // limpa os campos

        try {
            ProdutoDao dao = new ProdutoDao();
            List<Produto> lista = dao.buscar("");

            for (Produto produto : lista) {
                String[] linhadaTabela = {
                    String.valueOf(produto.getId()),
                    produto.getNomeProduto(),
                    produto.getUnidadeDeMedida(),
                    String.valueOf(produto.getValor())
                };
                modelo.addRow(linhadaTabela); // adiciona uma linha na tabela

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar: " + e.getMessage());

        }
    }

    private void atualizaValorTotal(Double valor) {
        Double valorTotal = Double.parseDouble(tfValorTNovoP.getText());

        Double total = valor + valorTotal;
        tfValorTNovoP.setText(total.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarPedido;
    private javax.swing.JComboBox<String> cbMesa;
    private javax.swing.JLabel lblAdicionar;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIconAddRem;
    private javax.swing.JLabel lblItensP;
    private javax.swing.JLabel lblItensP1;
    private javax.swing.JLabel lblItensP2;
    private javax.swing.JLabel lblItensP3;
    private javax.swing.JLabel lblItensP4;
    private javax.swing.JLabel lblItensP5;
    private javax.swing.JLabel lblItensP6;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblMesa1;
    private javax.swing.JLabel lblMesa2;
    private javax.swing.JLabel lblMesa3;
    private javax.swing.JLabel lblMesa4;
    private javax.swing.JLabel lblMesa5;
    private javax.swing.JLabel lblMesa6;
    private javax.swing.JLabel lblPedidosMesa;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JLabel lblTerminal;
    private javax.swing.JLabel lblValorT;
    private javax.swing.JLabel lblValorT1;
    private javax.swing.JLabel lblValorT2;
    private javax.swing.JLabel lblValorT3;
    private javax.swing.JLabel lblValorT4;
    private javax.swing.JLabel lblValorT5;
    private javax.swing.JLabel lblValorT6;
    private javax.swing.JLabel lblValorTNovoP;
    private javax.swing.JPanel pCabecalho;
    private javax.swing.JPanel pMesa1;
    private javax.swing.JPanel pMesa2;
    private javax.swing.JPanel pMesa3;
    private javax.swing.JPanel pMesa4;
    private javax.swing.JPanel pMesa5;
    private javax.swing.JPanel pMesa6;
    private javax.swing.JPanel pMesas;
    private javax.swing.JPanel pNovoPedido;
    private javax.swing.JPanel pPedidosMesa;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pRodaPe;
    private javax.swing.JScrollPane spItensP;
    private javax.swing.JScrollPane spPedidosMesa;
    private javax.swing.JScrollPane spProdutos;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JTable tblItensP;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfValorT;
    private javax.swing.JTextField tfValorTNovoP;
    // End of variables declaration//GEN-END:variables
}
